version: '3'

services:
  db:
    container_name: mysql-db
    image: mysql:oracle
    volumes:
      - world-db:/var/lib/mysql
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: heroesDB

    restart: always
  phpMyAdmin:
    container_name: phpMyAdmin
    depends_on:
      - db
    image: phpmyadmin:apache
    ports:
      - 8080:80
    restart: always

volumes:
  world-db:
    external: false
      

