version: '3'

services:
  db:
    container_name: postgres-db
    image: postgres:15.1
    volumes:
      - pg-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    restart: always
  


  pgAdmin:
    container_name: pgAdmin
    depends_on:
      - db
    image: dpage/pgadmin4:6.18
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 80:80
    environment:
       PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    restart: always


volumes:
  pg-db:
  pgadmin-data:
    external: false
      
      